"""empty message

Revision ID: a44150da90e3
Revises: efd4e6f8e7c0
Create Date: 2024-04-14 15:16:30.862812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44150da90e3'
down_revision = 'efd4e6f8e7c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gemini_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_type', sa.String(length=12), nullable=False))
        batch_op.add_column(sa.Column('mode', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gemini_setting', schema=None) as batch_op:
        batch_op.drop_column('mode')
        batch_op.drop_column('object_type')

    # ### end Alembic commands ###
