version: "3"
services:
  nonebot:
    build: .
    container_name: nonebot
    ports:
      - "8080:8080" # 映射端口到宿主机 宿主机端口:容器端口
    env_file:
      - ".env.prod"
    environment:
      - ENVIRONMENT=prod
      - APP_MODULE=bot:app
      - MAX_WORKERS=1
    # network_mode: bridge
  qsign:
    image: xzhouqd/qsign:8.9.63
    # ports:
      # - "8080:8080"  # {external_port}:{internal_port}
    environment:
      - PORT=8080
      - COUNT=3
      - ANDROID_ID=5d5a636ddbe3286f
    container_name: qsign
    restart: always
  cqhttp:
    image: ghcr.io/mrs4s/go-cqhttp:master
    # ports: 
      # - "8081:8080"
    volumes:
      - ./_cqhttp/:/data/
      - ./bin:/app/bin/
      - ./data:/app/data/
    # network_mode: bridge

