"""remove shortcut.enabled

迁移 ID: e0ce142785b0
父迁移: 918ce1172287
创建时间: 2024-09-10 18:32:09.784247

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e0ce142785b0'
down_revision: str | Sequence[str] | None = '918ce1172287'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_shortcut', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_shortcut', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
