"""add friend request

迁移 ID: 76459b795155
父迁移: f33404bd8f8d
创建时间: 2024-10-16 12:07:05.608039

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '76459b795155'
down_revision: str | Sequence[str] | None = 'f33404bd8f8d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_friendrequest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('valid', 'accepted', 'denied', 'invalidated', name='invitationstate'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utility_friendrequest')),
    info={'bind_key': 'utility'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utility_friendrequest')
    # ### end Alembic commands ###
