"""init group util

迁移 ID: e356940c4418
父迁移: 
创建时间: 2024-09-28 11:04:33.445679

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e356940c4418'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('utility',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_groupinvitation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inviter_id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('valid', 'accepted', 'denied', name='invitationstate'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utility_groupinvitation')),
    info={'bind_key': 'utility'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utility_groupinvitation')
    # ### end Alembic commands ###
