"""init bp

迁移 ID: 745cdf3b22b9
父迁移: 
创建时间: 2024-09-23 20:29:37.025121

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '745cdf3b22b9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('bracket_closer',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bracket_closer_enabled',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_bracket_closer_enabled')),
    info={'bind_key': 'bracket_closer'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bracket_closer_enabled')
    # ### end Alembic commands ###
