"""init

迁移 ID: 1c89472a60cd
父迁移: 
创建时间: 2024-09-11 22:17:41.563055

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1c89472a60cd'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('nm',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nm_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nm_history')),
    info={'bind_key': 'nm'}
    )
    op.create_table('nm_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=12), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nm_setting')),
    info={'bind_key': 'nm'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nm_setting')
    op.drop_table('nm_history')
    # ### end Alembic commands ###
